# Generated by Django 4.2.2 on 2023-07-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundalik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
